export const COUNTRIES = [
  { name: "Afghanistan", code: "AF", currency: "؋" },
  { name: "Albania", code: "AL", currency: "L" },
  { name: "Algeria", code: "DZ", currency: "د.ج" },
  { name: "Andorra", code: "AD", currency: "€" },
  { name: "Angola", code: "AO", currency: "Kz" },
  { name: "Antigua and Barbuda", code: "AG", currency: "$" },
  { name: "Argentina", code: "AR", currency: "$" },
  { name: "Armenia", code: "AM", currency: "֏" },
  { name: "Australia", code: "AU", currency: "$" },
  { name: "Austria", code: "AT", currency: "€" },
  { name: "Azerbaijan", code: "AZ", currency: "₼" },
  { name: "Bahamas", code: "BS", currency: "$" },
  { name: "Bahrain", code: "BH", currency: ".د.ب" },
  { name: "Bangladesh", code: "BD", currency: "৳" },
  { name: "Barbados", code: "BB", currency: "$" },
  { name: "Belarus", code: "BY", currency: "Br" },
  { name: "Belgium", code: "BE", currency: "€" },
  { name: "Belize", code: "BZ", currency: "$" },
  { name: "Benin", code: "BJ", currency: "Fr" },
  { name: "Bhutan", code: "BT", currency: "Nu." },
  { name: "Bolivia", code: "BO", currency: "Bs." },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "KM" },
  { name: "Botswana", code: "BW", currency: "P" },
  { name: "Brazil", code: "BR", currency: "R$" },
  { name: "Brunei", code: "BN", currency: "$" },
  { name: "Bulgaria", code: "BG", currency: "лв" },
  { name: "Burkina Faso", code: "BF", currency: "Fr" },
  { name: "Burundi", code: "BI", currency: "Fr" },
  { name: "Cabo Verde", code: "CV", currency: "Esc" },
  { name: "Cambodia", code: "KH", currency: "៛" },
  { name: "Cameroon", code: "CM", currency: "Fr" },
  { name: "Canada", code: "CA", currency: "$" },
  { name: "Central African Republic", code: "CF", currency: "Fr" },
  { name: "Chad", code: "TD", currency: "Fr" },
  { name: "Chile", code: "CL", currency: "$" },
  { name: "China", code: "CN", currency: "¥" },
  { name: "Colombia", code: "CO", currency: "$" },
  { name: "Comoros", code: "KM", currency: "Fr" },
  { name: "Congo, Democratic Republic of the", code: "CD", currency: "Fr" },
  { name: "Congo, Republic of the", code: "CG", currency: "Fr" },
  { name: "Costa Rica", code: "CR", currency: "₡" },
  { name: "Croatia", code: "HR", currency: "€" },
  { name: "Cuba", code: "CU", currency: "$" },
  { name: "Cyprus", code: "CY", currency: "€" },
  { name: "Czech Republic", code: "CZ", currency: "Kč" },
  { name: "Denmark", code: "DK", currency: "kr" },
  { name: "Djibouti", code: "DJ", currency: "Fr" },
  { name: "Dominica", code: "DM", currency: "$" },
  { name: "Dominican Republic", code: "DO", currency: "RD$" },
  { name: "East Timor (Timor-Leste)", code: "TL", currency: "$" },
  { name: "Ecuador", code: "EC", currency: "$" },
  { name: "Egypt", code: "EG", currency: "£" },
  { name: "El Salvador", code: "SV", currency: "$" },
  { name: "Equatorial Guinea", code: "GQ", currency: "Fr" },
  { name: "Eritrea", code: "ER", currency: "Nfk" },
  { name: "Estonia", code: "EE", currency: "€" },
  { name: "Eswatini", code: "SZ", currency: "L" },
  { name: "Ethiopia", code: "ET", currency: "Br" },
  { name: "Fiji", code: "FJ", currency: "$" },
  { name: "Finland", code: "FI", currency: "€" },
  { name: "France", code: "FR", currency: "€" },
  { name: "Gabon", code: "GA", currency: "Fr" },
  { name: "Gambia", code: "GM", currency: "D" },
  { name: "Georgia", code: "GE", currency: "₾" },
  { name: "Germany", code: "DE", currency: "€" },
  { name: "Ghana", code: "GH", currency: "₵" },
  { name: "Greece", code: "GR", currency: "€" },
  { name: "Grenada", code: "GD", currency: "$" },
  { name: "Guatemala", code: "GT", currency: "Q" },
  { name: "Guinea", code: "GN", currency: "Fr" },
  { name: "Guinea-Bissau", code: "GW", currency: "Fr" },
  { name: "Guyana", code: "GY", currency: "$" },
  { name: "Haiti", code: "HT", currency: "G" },
  { name: "Honduras", code: "HN", currency: "L" },
  { name: "Hungary", code: "HU", currency: "Ft" },
  { name: "Iceland", code: "IS", currency: "kr" },
  { name: "India", code: "IN", currency: "₹" },
  { name: "Indonesia", code: "ID", currency: "Rp" },
  { name: "Iran", code: "IR", currency: "﷼" },
  { name: "Iraq", code: "IQ", currency: "ع.د" },
  { name: "Ireland", code: "IE", currency: "€" },
  { name: "Israel", code: "IL", currency: "₪" },
  { name: "Italy", code: "IT", currency: "€" },
  { name: "Ivory Coast", code: "CI", currency: "Fr" },
  { name: "Jamaica", code: "JM", currency: "J$" },
  { name: "Japan", code: "JP", currency: "¥" },
  { name: "Jordan", code: "JO", currency: "د.ا" },
  { name: "Kazakhstan", code: "KZ", currency: "₸" },
  { name: "Kenya", code: "KE", currency: "Sh" },
  { name: "Kiribati", code: "KI", currency: "$" },
  { name: "Korea, North", code: "KP", currency: "₩" },
  { name: "Korea, South", code: "KR", currency: "₩" },
  { name: "Kosovo", code: "XK", currency: "€" },
  { name: "Kuwait", code: "KW", currency: "د.ك" },
  { name: "Kyrgyzstan", code: "KG", currency: "с" },
  { name: "Laos", code: "LA", currency: "₭" },
  { name: "Latvia", code: "LV", currency: "€" },
  { name: "Lebanon", code: "LB", currency: "ل.ل" },
  { name: "Lesotho", code: "LS", currency: "L" },
  { name: "Liberia", code: "LR", currency: "$" },
  { name: "Libya", code: "LY", currency: "ل.د" },
  { name: "Liechtenstein", code: "LI", currency: "Fr" },
  { name: "Lithuania", code: "LT", currency: "€" },
  { name: "Luxembourg", code: "LU", currency: "€" },
  { name: "Madagascar", code: "MG", currency: "Ar" },
  { name: "Malawi", code: "MW", currency: "MK" },
  { name: "Malaysia", code: "MY", currency: "RM" },
  { name: "Maldives", code: "MV", currency: "Rf" },
  { name: "Mali", code: "ML", currency: "Fr" },
  { name: "Malta", code: "MT", currency: "€" },
  { name: "Marshall Islands", code: "MH", currency: "$" },
  { name: "Mauritania", code: "MR", currency: "UM" },
  { name: "Mauritius", code: "MU", currency: "₨" },
  { name: "Mexico", code: "MX", currency: "$" },
  { name: "Micronesia", code: "FM", currency: "$" },
  { name: "Moldova", code: "MD", currency: "L" },
  { name: "Monaco", code: "MC", currency: "€" },
  { name: "Mongolia", code: "MN", currency: "₮" },
  { name: "Montenegro", code: "ME", currency: "€" },
  { name: "Morocco", code: "MA", currency: "د.م." },
  { name: "Mozambique", code: "MZ", currency: "MT" },
  { name: "Myanmar (Burma)", code: "MM", currency: "Ks" },
  { name: "Namibia", code: "NA", currency: "$" },
  { name: "Nauru", code: "NR", currency: "$" },
  { name: "Nepal", code: "NP", currency: "₨" },
  { name: "Netherlands", code: "NL", currency: "€" },
  { name: "New Zealand", code: "NZ", currency: "$" },
  { name: "Nicaragua", code: "NI", currency: "C$" },
  { name: "Niger", code: "NE", currency: "Fr" },
  { name: "Nigeria", code: "NG", currency: "₦" },
  { name: "North Macedonia", code: "MK", currency: "ден" },
  { name: "Norway", code: "NO", currency: "kr" },
  { name: "Oman", code: "OM", currency: "ر.ع." },
  { name: "Pakistan", code: "PK", currency: "₨" },
  { name: "Palau", code: "PW", currency: "$" },
  { name: "Palestine State", code: "PS", currency: "₪" },
  { name: "Panama", code: "PA", currency: "B/." },
  { name: "Papua New Guinea", code: "PG", currency: "K" },
  { name: "Paraguay", code: "PY", currency: "₲" },
  { name: "Peru", code: "PE", currency: "S/." },
  { name: "Philippines", code: "PH", currency: "₱" },
  { name: "Poland", code: "PL", currency: "zł" },
  { name: "Portugal", code: "PT", currency: "€" },
  { name: "Qatar", code: "QA", currency: "ر.ق" },
  { name: "Romania", code: "RO", currency: "lei" },
  { name: "Russia", code: "RU", currency: "₽" },
  { name: "Rwanda", code: "RW", currency: "Fr" },
  { name: "Saint Kitts and Nevis", code: "KN", currency: "$" },
  { name: "Saint Lucia", code: "LC", currency: "$" },
  { name: "Saint Vincent and the Grenadines", code: "VC", currency: "$" },
  { name: "Samoa", code: "WS", currency: "T" },
  { name: "San Marino", code: "SM", currency: "€" },
  { name: "Sao Tome and Principe", code: "ST", currency: "Db" },
  { name: "Saudi Arabia", code: "SA", currency: "ر.س" },
  { name: "Senegal", code: "SN", currency: "Fr" },
  { name: "Serbia", code: "RS", currency: "дин." },
  { name: "Seychelles", code: "SC", currency: "₨" },
  { name: "Sierra Leone", code: "SL", currency: "Le" },
  { name: "Singapore", code: "SG", currency: "$" },
  { name: "Slovakia", code: "SK", currency: "€" },
  { name: "Slovenia", code: "SI", currency: "€" },
  { name: "Solomon Islands", code: "SB", currency: "$" },
  { name: "Somalia", code: "SO", currency: "Sh" },
  { name: "South Africa", code: "ZA", currency: "R" },
  { name: "South Sudan", code: "SS", currency: "£" },
  { name: "Spain", code: "ES", currency: "€" },
  { name: "Sri Lanka", code: "LK", currency: "Rs" },
  { name: "Sudan", code: "SD", currency: "ج.س." },
  { name: "Suriname", code: "SR", currency: "$" },
  { name: "Sweden", code: "SE", currency: "kr" },
  { name: "Switzerland", code: "CH", currency: "Fr" },
  { name: "Syria", code: "SY", currency: "£" },
  { name: "Taiwan", code: "TW", currency: "$" },
  { name: "Tajikistan", code: "TJ", currency: "ЅМ" },
  { name: "Tanzania", code: "TZ", currency: "Sh" },
  { name: "Thailand", code: "TH", currency: "฿" },
  { name: "Togo", code: "TG", currency: "Fr" },
  { name: "Tonga", code: "TO", currency: "T$" },
  { name: "Trinidad and Tobago", code: "TT", currency: "$" },
  { name: "Tunisia", code: "TN", currency: "د.ت" },
  { name: "Turkey", code: "TR", currency: "₺" },
  { name: "Turkmenistan", code: "TM", currency: "m" },
  { name: "Tuvalu", code: "TV", currency: "$" },
  { name: "Uganda", code: "UG", currency: "Sh" },
  { name: "Ukraine", code: "UA", currency: "₴" },
  { name: "United Arab Emirates", code: "AE", currency: "د.إ" },
  { name: "United Kingdom", code: "GB", currency: "£" },
  { name: "United States", code: "US", currency: "$" },
  { name: "Uruguay", code: "UY", currency: "$" },
  { name: "Uzbekistan", code: "UZ", currency: "so'm" },
  { name: "Vanuatu", code: "VU", currency: "Vt" },
  { name: "Vatican City", code: "VA", currency: "€" },
  { name: "Venezuela", code: "VE", currency: "Bs" },
  { name: "Vietnam", code: "VN", currency: "₫" },
  { name: "Yemen", code: "YE", currency: "﷼" },
  { name: "Zambia", code: "ZM", currency: "ZK" },
  { name: "Zimbabwe", code: "ZW", currency: "$" }
];
